spring:
  application:
    name: stock-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    enabled: true

logging:
  level:
    root: INFO
    fr.stockshop: INFO
